# Generated by Django 4.2.29 on 2026-03-17 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.CharField(default='hybrid', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_recommendations',
                'managed': True,
                'indexes': [models.Index(fields=['user', '-score'], name='user_recomm_user_id_556b02_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='UserProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('cart', 'Add to Cart'), ('purchase', 'Purchase'), ('review', 'Review')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_product_interactions',
                'managed': True,
                'indexes': [models.Index(fields=['user', 'product'], name='user_produc_user_id_4ef734_idx'), models.Index(fields=['product', 'interaction_type'], name='user_produc_product_05affc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_a', to='catalog.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_b', to='catalog.product')),
            ],
            options={
                'db_table': 'product_similarities',
                'managed': True,
                'indexes': [models.Index(fields=['product_a', '-score'], name='product_sim_product_5cd980_idx')],
                'unique_together': {('product_a', 'product_b')},
            },
        ),
    ]
